spring:
  thymeleaf:
    cache: false
  
  data:
    rest:
      basePath: /api
  datasource:
    password: 
    url: jdbc:mysql://127.0.0.1:3306/example_db
    username: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  
server:
  port: 8081
  
welcome:
  message: Hola Mundo
valor: 20, 30, 50, 70
  